#!/bin/bash

echo "Compilando el proyecto..."
g++ proyecto.cpp Archivos_cpp/*.cpp -I Archivos_hpp -o output/proyecto

if [ $? -eq 0 ]; then
    echo "Compilación exitosa."
    echo "Ejecutando el programa..."
    ./output/proyecto
else
    echo "Error en la compilación."
fi
